### ISSUE TITLE
enable elementary data quality

### ISSUE THREAD

**Issue by fatchat** [Antarang-Foundation/dbt_antarang#12]
In order to enable dbt test reporting via Elementary, we need to make two changes as described [here](https://docs.elementary-data.com/oss/quickstart/quickstart-cli-package)

1. Add to `packages.yml`:
```
packages:
  - package: elementary-data/elementary
    version: 0.15.2
    ## Docs: https://docs.elementary-data.com
```

2. Add to `dbt_project.yml`
```
models:
  ## see docs: https://docs.elementary-data.com/
  elementary:
    ## elementary models will be created in the schema '<your_schema>_elementary'
    +schema: "elementary"
    ## To disable elementary for dev, uncomment this:
    # enabled: "{{ target.name in ['prod'] }}"

# Required from dbt 1.8 and above for certain Elementary features (please see more details above)
#flags:
#  require_explicit_package_overrides_for_builtin_materializations: false
```
